#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#395b4de6'
TEXT='#395b4de6'
WRONG='#a44c24bb'
VERIFYING='#395b4de6'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$WRONG         \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"           \
--date-str="%A, %m-%d"       \
--verif-text="verifying"     \
--keylayout 1                \
--ignore-empty-password      \
